# Generated by Django 3.2.3 on 2021-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
    ]
