# Generated by Django 3.2.3 on 2021-05-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QNA',
            new_name='Post',
        ),
    ]
